### get list teams
GET https://api.clickup.com/api/v2/team HTTP/1.1
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7

### get list spaces in teams
GET https://api.clickup.com/api/v2/team/31592919/space?archived=false
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7

### get folders in space & its lists (lists of space without parent folder excluded)
GET https://api.clickup.com/api/v2/space/55620445/folder?archived=false
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7

### get folderless lists
GET https://api.clickup.com/api/v2/space/{space_id}/list?archived=false
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7

### get folder lists
GET https://api.clickup.com/api/v2/folder/{folder_id}/list?archived=false
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7

### get tasks list (subtasks included), subtask has parent fill ==  id of parent task
### time_spent - total tracked time on task/subtask
GET https://api.clickup.com/api/v2/list/211787826/task?archived=false&page=0&subtasks=true&include_closed=true
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7

### get list detail (has all statuses in list for auto switching)
GET https://api.clickup.com/api/v2/list/211787826
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7

### query time entry in range (time in milisecond date.getTime())
### https://stackoverflow.com/questions/8636617/how-to-get-start-and-end-of-day-in-javascript
### thoi gian duoc lay bat ke vat ngang => ko duoc filter
GET https://api.clickup.com/api/v2/team/31592919/time_entries?start_date=1669248000000&end_date=1669334399999
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7

### start time entry
POST https://api.clickup.com/api/v2/team/31592919/time_entries/start
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7

{
    "description": "start from api",
    "tid": "3w4p0uz",
    "billable": false,
    "tag":[],
}

### stop running time entry -> should call every time want to start new timer
POST https://api.clickup.com/api/v2/team/31592919/time_entries/stop
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7

### get running time entry
GET https://api.clickup.com/api/v2/team/31592919/time_entries/current
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7

### create time entry
POST https://api.clickup.com/api/v2/team/31592919/time_entries
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7
Content-Type: application/json

{
    "description":"create from TPomo",
    "tags":[],
    "start":1669200323838,
    "billable":false,
    "duration":50000,
    "assignee":1,
    "tid": "3w4p0uz",
    "via":"range"
}

### create track time (legacy) for task_id
POST https://api.clickup.com/api/v2/task/3waapk0/time
# POST httpbin.org/anything
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7
Content-Type: application/json

{
  "start": 1669275503000,
  "time": 100000
}

### get all tracked times of task
GET https://api.clickup.com/api/v2/task/3waapk0/time
Authorization: pk_49623558_0Y8IAAZ8BI2L48G3GG2Q5O1UFRGN8VA7
Content-Type: "application/json"
